[2022-12-05T00:11:10.171+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2022-12-05T00:11:10.188+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2022-12-05T00:11:10.189+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T00:11:10.190+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-05T00:11:10.190+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T00:11:10.208+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): greet> on 2022-12-04 00:00:00+00:00
[2022-12-05T00:11:10.240+0000] {standard_task_runner.py:55} INFO - Started process 19994 to run task
[2022-12-05T00:11:10.261+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'greet', 'scheduled__2022-12-04T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/songs.py', '--cfg-path', '/tmp/tmppm0pro63']
[2022-12-05T00:11:10.280+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask greet
[2022-12-05T00:11:10.512+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.greet scheduled__2022-12-04T00:00:00+00:00 [running]> on host 0d9ad98b0a1c
[2022-12-05T00:11:10.704+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-04T00:00:00+00:00
[2022-12-05T00:11:10.707+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/songs.py", line 23, in ReadData
    database="chinhook"
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2022-12-05T00:11:10.719+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=greet, execution_date=20221204T000000, start_date=20221205T001110, end_date=20221205T001110
[2022-12-05T00:11:10.727+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task greet (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 19994)
[2022-12-05T00:11:10.755+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-05T00:11:10.786+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-05T04:19:35.684+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2022-12-05T04:19:35.694+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2022-12-05T04:19:35.695+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T04:19:35.695+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-05T04:19:35.695+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-05T04:19:35.708+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): greet> on 2022-12-04 00:00:00+00:00
[2022-12-05T04:19:35.715+0000] {standard_task_runner.py:55} INFO - Started process 10232 to run task
[2022-12-05T04:19:35.720+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'greet', 'scheduled__2022-12-04T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmpw4c269m6']
[2022-12-05T04:19:35.722+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask greet
[2022-12-05T04:19:35.789+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.greet scheduled__2022-12-04T00:00:00+00:00 [running]> on host 0d175b7fb514
[2022-12-05T04:19:35.859+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-04T00:00:00+00:00
[2022-12-05T04:19:35.861+0000] {logging_mixin.py:137} INFO - hello
[2022-12-05T04:19:35.862+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-05T04:19:35.871+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=greet, execution_date=20221204T000000, start_date=20221205T041935, end_date=20221205T041935
[2022-12-05T04:19:35.892+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-05T04:19:35.906+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
