[2022-12-07T22:48:28.874+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-06T00:00:00+00:00 [queued]>
[2022-12-07T22:48:28.889+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-06T00:00:00+00:00 [queued]>
[2022-12-07T22:48:28.891+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T22:48:28.893+0000] {taskinstance.py:1284} INFO - Starting attempt 28 of 32
[2022-12-07T22:48:28.895+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T22:48:28.911+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): greet> on 2022-12-06 00:00:00+00:00
[2022-12-07T22:48:28.918+0000] {standard_task_runner.py:55} INFO - Started process 35363 to run task
[2022-12-07T22:48:28.924+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'greet', 'scheduled__2022-12-06T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmp9f7vvreb']
[2022-12-07T22:48:28.927+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask greet
[2022-12-07T22:48:29.016+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.greet scheduled__2022-12-06T00:00:00+00:00 [running]> on host 0d175b7fb514
[2022-12-07T22:48:29.104+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=28
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-06T00:00:00+00:00
[2022-12-07T22:48:29.113+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 21, in ReadData
    database="postgres"
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known

[2022-12-07T22:48:29.128+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=greet, execution_date=20221206T000000, start_date=20221207T224828, end_date=20221207T224829
[2022-12-07T22:48:29.140+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task greet (could not translate host name "db" to address: Name or service not known
; 35363)
[2022-12-07T22:48:29.175+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-07T22:48:29.196+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
