[2022-12-07T22:56:33.682+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-06T00:00:00+00:00 [queued]>
[2022-12-07T22:56:33.694+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-06T00:00:00+00:00 [queued]>
[2022-12-07T22:56:33.696+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T22:56:33.697+0000] {taskinstance.py:1284} INFO - Starting attempt 32 of 32
[2022-12-07T22:56:33.697+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T22:56:33.723+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): greet> on 2022-12-06 00:00:00+00:00
[2022-12-07T22:56:33.743+0000] {standard_task_runner.py:55} INFO - Started process 35933 to run task
[2022-12-07T22:56:33.749+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'greet', 'scheduled__2022-12-06T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmpqxaabx83']
[2022-12-07T22:56:33.758+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask greet
[2022-12-07T22:56:33.884+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.greet scheduled__2022-12-06T00:00:00+00:00 [running]> on host 0d175b7fb514
[2022-12-07T22:56:33.987+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=32
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-06T00:00:00+00:00
[2022-12-07T22:56:34.010+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 21, in ReadData
    database="postgres"
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known

[2022-12-07T22:56:34.029+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=first_dag, task_id=greet, execution_date=20221206T000000, start_date=20221207T225633, end_date=20221207T225634
[2022-12-07T22:56:34.038+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task greet (could not translate host name "db" to address: Name or service not known
; 35933)
[2022-12-07T22:56:34.087+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-07T22:56:34.109+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
