[2022-12-08T04:16:46.300+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-07T00:00:00+00:00 [queued]>
[2022-12-08T04:16:46.307+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-07T00:00:00+00:00 [queued]>
[2022-12-08T04:16:46.307+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T04:16:46.308+0000] {taskinstance.py:1284} INFO - Starting attempt 18 of 19
[2022-12-08T04:16:46.308+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T04:16:46.316+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): greet> on 2022-12-07 00:00:00+00:00
[2022-12-08T04:16:46.321+0000] {standard_task_runner.py:55} INFO - Started process 4016 to run task
[2022-12-08T04:16:46.324+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'greet', 'scheduled__2022-12-07T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmpe6_wvd07']
[2022-12-08T04:16:46.328+0000] {standard_task_runner.py:83} INFO - Job 71: Subtask greet
[2022-12-08T04:16:46.385+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.greet scheduled__2022-12-07T00:00:00+00:00 [running]> on host d6a5ea0de8c8
[2022-12-08T04:16:46.438+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=18
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-07T00:00:00+00:00
[2022-12-08T04:16:46.443+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 21, in ReadData
    database="postgres"
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "***-postgres-1" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2022-12-08T04:16:46.452+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=greet, execution_date=20221207T000000, start_date=20221208T041646, end_date=20221208T041646
[2022-12-08T04:16:46.458+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 71 for task greet (connection to server at "***-postgres-1" (172.19.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 4016)
[2022-12-08T04:16:46.496+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-08T04:16:46.511+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
