[2022-12-06T01:59:07.667+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06T01:59:07.680+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: first_dag.greet scheduled__2022-12-05T00:00:00+00:00 [queued]>
[2022-12-06T01:59:07.681+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T01:59:07.682+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2022-12-06T01:59:07.683+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-06T01:59:07.707+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): greet> on 2022-12-05 00:00:00+00:00
[2022-12-06T01:59:07.717+0000] {standard_task_runner.py:55} INFO - Started process 52279 to run task
[2022-12-06T01:59:07.727+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'greet', 'scheduled__2022-12-05T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/song.py', '--cfg-path', '/tmp/tmp_8qqu_ol']
[2022-12-06T01:59:07.730+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask greet
[2022-12-06T01:59:07.833+0000] {task_command.py:389} INFO - Running <TaskInstance: first_dag.greet scheduled__2022-12-05T00:00:00+00:00 [running]> on host 0d175b7fb514
[2022-12-06T01:59:07.950+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-05T00:00:00+00:00
[2022-12-06T01:59:07.953+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/song.py", line 21, in ReadData
    database="chinhook"
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2022-12-06T01:59:07.968+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=greet, execution_date=20221205T000000, start_date=20221206T015907, end_date=20221206T015907
[2022-12-06T01:59:07.982+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task greet (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 52279)
[2022-12-06T01:59:08.020+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-06T01:59:08.044+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
