[2022-12-11T14:47:01.685+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ArtistRevenue.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:47:01.692+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ArtistRevenue.ReadData scheduled__2022-12-10T00:00:00+00:00 [queued]>
[2022-12-11T14:47:01.693+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:47:01.693+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-11T14:47:01.694+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T14:47:01.707+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ReadData> on 2022-12-10 00:00:00+00:00
[2022-12-11T14:47:01.715+0000] {standard_task_runner.py:55} INFO - Started process 9551 to run task
[2022-12-11T14:47:01.720+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ArtistRevenue', 'ReadData', 'scheduled__2022-12-10T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/artist_revenue.py', '--cfg-path', '/tmp/tmp8kvrjsc6']
[2022-12-11T14:47:01.727+0000] {standard_task_runner.py:83} INFO - Job 213: Subtask ReadData
[2022-12-11T14:47:01.784+0000] {task_command.py:389} INFO - Running <TaskInstance: ArtistRevenue.ReadData scheduled__2022-12-10T00:00:00+00:00 [running]> on host 83e68f36074a
[2022-12-11T14:47:01.834+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gama Ariefsadya
AIRFLOW_CTX_DAG_ID=ArtistRevenue
AIRFLOW_CTX_TASK_ID=ReadData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T00:00:00+00:00
[2022-12-11T14:47:01.856+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/artist_revenue.py", line 44, in ReadData
    revenues=json.dumps(revenues)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[2022-12-11T14:47:01.865+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=ArtistRevenue, task_id=ReadData, execution_date=20221210T000000, start_date=20221211T144701, end_date=20221211T144701
[2022-12-11T14:47:01.873+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 213 for task ReadData (Object of type datetime is not JSON serializable; 9551)
[2022-12-11T14:47:01.892+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-11T14:47:01.912+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
